#!/bin/bash

# @file        sofa
# @brief       CLI for parsing & extracting SOFA feed data.
# @description Allows for easier filtering of the MacAdmins SOFA JSON feed by device, model, delay, or version
# comparisons, as well as the output of a single matching SecurityRelease JSON object or property therein.
#
# This tool is not endorsed by or affiliated with the macadmins/sofa project.
# This tool requires that 'jq' is installed, this is standard on macOS 15+
#
# @option --version                   Displays Version
# @option --device [optional_device]  Filter JSON by Device ID; will detect from system if not given
# @option --model [optional_model]    Filter JSON by Model ID; will detect from system if not given
# @option --delay [delay]             Filter JSON by delay, given in days
# @option --eq [version]              Filter JSON by ProductVersion equal to given version
# @option --gt [version]              Filter JSON by ProductVersion greater than given version
# @option --lt [version]              Filter JSON by ProductVersion less than than given version
# @option --gte [version]             Filter JSON by ProductVersion greater than or equal to than given version
# @option --lte [version]             Filter JSON by ProductVersion greater than or equal to than given version
# @option --latest                    Return JSON object for the latest SecurityRelease version, in filtered data
# @option --next [version]            Return JSON object for the SecurityRelease w/ "next" version, in filtered data
# @arg    $1                          Optional JQ style filters applied to JSON output
#
# @license   Apache v2 (https://github.com/jonesiscoding/sofa-cli/blob/main/LICENSE)
# @copyright Copyright 2026 AMJones <am@jonesiscoding.com>
# @version
# @revision
# @built
# @uploaded

# Script Info
selfDir="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P )"
selfVer="##VERSION##"
selfRepo="https://github.com/jonesiscoding/sofa-cli"

# shellcheck source=./lib/_version.sh
source "$selfDir/lib/_version.sh"
# shellcheck source=./lib/_jq.sh
source "$selfDir/lib/_jq.sh"
# shellcheck source=./lib/_sofa.sh
source "$selfDir/lib/_sofa.sh"

## region ###################################### Usage Help

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # @description Outputs help text
  # @noargs
  # @stdout string Help Text
  function output-usage() {
    cat << EOF

sofa-cli $selfVer
  Allows for easier filtering of the MacAdmins SOFA JSON feed by device, model, delay, or version comparisons
  as well as the output of a single matching SecurityRelease JSON object or property therein.

Syntax:

  sofa                                            (Displays the unfiltered SOFA feed)
  sofa --device --next 26.3.1 '.ProductVersion'   (Skips 26.3.2 to display 26.4 unless you on a MacBook Neo)
  sofa --lte 15.7                                 (Filters to versions less than or equal to 15.7.x)
  sofa --lte 15.7.4                               (Filters to versions less than or equal to 15.7.4)
  sofa --model Mac15,13 --latest                  (Shows SecurityRelease JSON for latest version eligible)

Query language appropriate for JQ may be used after any flags to further filter results.

Filter Flags

  --device <optional_device>  Filter JSON by Device ID; will detect from system if not given
  --model <optional_model>    Filter JSON by Model ID; will detect from system if not given
  --eq <version>              Filter JSON by ProductVersion equal to the given version
  --gt <version>              Filter JSON by ProductVersion greater than the given version
  --lt <version>              Filter JSON by ProductVersion less than given version
  --gte <version>             Filter JSON by ProductVersion greater than or equal to the given version
  --lte <version>             Filter JSON by ProductVersion greater than or equal to the given version

Extraction Flags

These flags extract data from the feed, and are applied after any filter flags.

  --latest                    Extracts the SecurityRelease with the latest version number
  --next <version>            Extracts the SecurityRelease with the next logical version to the given version

Other Flags

  --version                   Shows version & quits.
  --help                      Shows this help text & quits.

EOF
  }

## endregion ################################### Usage Help

## region ###################################### Input Handling

  assert::jq || exit "$exitNoJQ"
  # jq, where are you?
  ! which jq > /dev/null 2>&1 && PATH="$(dirname "$JQ_BIN"):$PATH"

  isNext=false
  isLatest=false
  sofaCache=$(sofa::json)
  sofa=$(cat "$sofaCache")
  query=()
  while [ "$1" != "" ]; do
    case "$1" in
        --version )
          echo "sofa-cli v${selfVer}"
          echo "(${selfRepo})"
          exit 0
          ;;
        --help )
          output-usage
          exit 0
          ;;
        --device )
          device="$2"
          echo "$device" | grep -qE "^\-\-" && device=""
          [ -n "$device" ] && shift;
          [ -z "$device" ] && ! $isMacOS && echo "${RED}ERROR:${RESET} You must specify a device with the --device flag." && exit 1
          sofa=$(sofa::filter::device "$device" <<< "$sofa");
          ;;
        --gte )
          sofa=$(sofa::filter::ver "gte" "$2" <<< "$sofa")
          shift;
          ;;
        --gt )
          sofa=$(sofa::filter::ver "gte" "$2" <<< "$sofa")
          shift;
          ;;
        --lte | --max )
          sofa=$(sofa::filter::ver "lte" "$2" <<< "$sofa")
          shift;
          ;;
        --lt )
          sofa=$(sofa::filter::ver "lt" "$2" <<< "$sofa")
          shift;
          ;;
        --eq )
          sofa=$(sofa::filter::ver "eq" "$2" <<< "$sofa")
          shift;
          ;;
        --model )
          model="$2"
          echo "$model" | grep -qE "^\-\-" && model=""
          [ -n "$model" ] && shift;
          [ -z "$model" ] && ! $isMacOS && echo "${RED}ERROR:${RESET} You must specify a model with the --model flag." && exit 1
          sofa=$(sofa::filter::model "$model" <<< "$sofa");
          ;;
        --delay )
          delay="$2"; shift;
          sofa=$(sofa::filter::delay "$delay" <<< "$sofa")
          ;;
        --next )
          isNext=true
          myVersion="$2"
          echo "$myVersion" | grep -qE "^\-\-" && myVersion=""
          [ -n "$myVersion" ] && shift;
          [ -z "$myVersion" ] && ! $isMacOS && echo "${RED}ERROR:${RESET} You must specify a version with the --next flag." && exit 1
          ;;
        --latest )                     isLatest=true    ;;
        *)                             query+=("$1"); ;;
    esac
    shift # move to next kv pair
  done

  ## endregion ################################### Input Handling

  ## region ###################################### Controller

  if $isNext || $isLatest; then
    if $isNext; then
      obj=$(sofa::ver::next "$myVersion" <<< "$sofa")
    elif $isLatest; then
      obj=$(sofa::ver::latest <<< "$sofa")
    fi

    if [ -n "$obj" ]; then
      if output=$(jq -r "${query[@]}" <<< "$obj"); then
        case "$(echo "$output" | xargs)" in
          \{*\}|\[*\]) jq . <<< "$output" ;;
          *)           echo "$output"     ;;
        esac
        exit 0
      else
        exit $?
      fi
    fi

    exit 1
  fi

  # Show Output
  [ ${#query[@]} -eq 0 ] && query+=(.)
  if output=$(jq -r "${query[@]}" <<< "$sofa"); then
    case "$(echo "$output" | xargs)" in
      \{*\}|\[*\]) jq . <<< "$output" ;;
      *)           echo "$output"     ;;
    esac
    exit 0
  else
    exit $?
  fi
fi

## endregion ################################### Controller
